name: CI/CD
on:
  push:
    branches: [ master ]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Set Up python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          python -m unittest discover tests/
  deployment:
    needs: test_suite
    runs-on: ubuntu-latest
    steps:
      - name: Fresh clone & repo install
        uses: appleboy/ssh-action@master
        with:
          host: 54.226.40.64
          username: github-actions
          key: ${{secrets.SSH_KEY}}
          port: 22
          script: |
            rm -rf fuel_app
            git clone https://github.com/habibah-adam/fuel_app.git
            python3.8 -m venv /home/github-actions/fuel_app/venv
            /home/github-actions/fuel_app/venv/bin/pip install -r /home/github-actions/fuel_app/requirements.txt




